coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
  
comment:
  layout: "header, diff, flags, files"
  behavior: default

github_checks:
  annotations: true